[package]
name = "pangaea"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"

# [workspace]
# resolver = "2"

[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

