name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup SDL3
        uses: libsdl-org/setup-sdl@main
        with:
          version: 3-latest

      - name: Build
        run: make

      - name: Clean
        run: make clean
